"""adiciona constraints de status e priority

Revision ID: 8e47420dc053
Revises: bd18851d60b3
Create Date: 2026-08-25 13:12:19.812097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e47420dc053'
down_revision = 'bd18851d60b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_todo_priority_valido', "priority IN ('baixa', 'media', 'alta')")
        batch_op.create_check_constraint('ck_todo_status_valido', "status IN ('todo', 'doing', 'done')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint('ck_todo_status_valido', type_='check')
        batch_op.drop_constraint('ck_todo_priority_valido', type_='check')

    # ### end Alembic commands ###
